services:
  rclone:
    image: chunyingh/rclone
    pull_policy: build
    build: .
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
      - DAC_READ_SEARCH
    ports:
      - "5572:5572/tcp"
    environment:
      - RC_USER=rclon3
      - RC_PASS=gui
    volumes:
      - ./excluded.txt:/excluded.txt:ro
      - ./rclone.conf:/root/.config/rclone/rclone.conf:ro
